In [1]:
import pandas as pd 
import numpy as np 
import yfinance as yf

In [3]:
data = pd.read_html('https://en.wikipedia.org/wiki/Nasdaq-100')[4]
data.head()

,Company,Ticker,GICS Sector,GICS Sub-Industry
0,Adobe Inc.,ADBE,Information Technology,Application Software
1,Airbnb,ABNB,Consumer Discretionary,"Hotels, Resorts & Cruise Lines"
2,Alphabet Inc. (Class A),GOOGL,Communication Services,Interactive Media & Services
3,Alphabet Inc. (Class C),GOOG,Communication Services,Interactive Media & Services
4,Amazon,AMZN,Consumer Discretionary,Broadline Retail

In [4]:
tickers = data['Ticker'].tolist()

In [6]:
df = yf.download(tickers,start='2010-01-01')['Adj Close']

[*********************100%%**********************]  101 of 101 completed

In [7]:
df.head()

Ticker,AAPL,ABNB,ADBE,ADI,ADP,ADSK,AEP,AMAT,AMD,AMGN,...,TSLA,TTD,TTWO,TXN,VRSK,VRTX,WBD,WDAY,XEL,ZS
Date,,,,,,,,,,,,,,,,,,,,,
2010-01-04,6.461977,NaN,37.090000,22.441116,26.572712,25.670000,19.888439,11.185110,9.70,41.200787,...,NaN,NaN,10.40,17.924688,28.804266,44.240002,15.840572,NaN,12.788527,NaN
2010-01-05,6.473148,NaN,37.700001,22.405687,26.430025,25.280001,19.660748,11.099072,9.71,40.843872,...,NaN,NaN,10.47,17.821318,28.997257,42.779999,16.463976,NaN,12.636855,NaN
2010-01-06,6.370184,NaN,37.619999,22.363167,26.367983,25.340000,19.859974,11.075608,9.57,40.536942,...,NaN,NaN,10.44,17.690376,29.373594,42.029999,16.709249,NaN,12.661130,NaN
2010-01-07,6.358407,NaN,36.889999,22.186022,26.355572,25.480000,20.030743,10.958277,9.47,40.165764,...,NaN,NaN,10.39,17.745504,29.325346,41.500000,16.699030,NaN,12.606527,NaN
2010-01-08,6.400680,NaN,36.689999,22.313564,26.318335,26.260000,20.269812,11.380653,9.43,40.522678,...,NaN,NaN,10.42,18.152103,28.949007,40.669998,16.750128,NaN,12.612591,NaN

In [8]:
df.dropna(axis=1,inplace=True)

In [9]:
df.head(3)

Ticker,AAPL,ADBE,ADI,ADP,ADSK,AEP,AMAT,AMD,AMGN,AMZN,...,SBUX,SMCI,SNPS,TMUS,TTWO,TXN,VRSK,VRTX,WBD,XEL
Date,,,,,,,,,,,,,,,,,,,,,
2010-01-04,6.461977,37.090000,22.441116,26.572712,25.670000,19.888439,11.185110,9.70,41.200787,6.6950,...,8.943929,11.52,22.440001,13.047586,10.40,17.924688,28.804266,44.240002,15.840572,12.788527
2010-01-05,6.473148,37.700001,22.405687,26.430025,25.280001,19.660748,11.099072,9.71,40.843872,6.7345,...,9.153461,11.27,22.250000,13.080329,10.47,17.821318,28.997257,42.779999,16.463976,12.636855
2010-01-06,6.370184,37.619999,22.363167,26.367983,25.340000,19.859974,11.075608,9.57,40.536942,6.6125,...,9.087496,11.49,22.209999,12.196301,10.44,17.690376,29.373594,42.029999,16.709249,12.661130

Calculating monthly return

In [12]:
ret_mtl = (df.pct_change()+1)[1:].resample('ME').prod() 
ret_mtl.head(5)

Ticker,AAPL,ADBE,ADI,ADP,ADSK,AEP,AMAT,AMD,AMGN,AMZN,...,SBUX,SMCI,SNPS,TMUS,TTWO,TXN,VRSK,VRTX,WBD,XEL
Date,,,,,,,,,,,,,,,,,,,,,
2010-01-31,0.897435,0.870855,0.851279,0.952370,0.926763,0.991700,0.851748,0.769072,1.013167,0.936594,...,0.945336,1.075521,0.947861,0.706399,0.892308,0.869486,0.942044,0.867993,0.956774,0.985769
2010-02-28,1.065396,1.072755,1.084570,1.020103,1.171921,0.982246,1.009773,1.060322,0.968023,0.944103,...,1.051400,1.211461,1.029619,1.095915,1.036638,1.083556,1.006401,1.055729,1.050236,1.001443
2010-03-31,1.148470,1.020779,0.992337,1.077120,1.053802,1.016657,1.100490,1.171934,1.057057,1.146706,...,1.059363,1.151233,1.021461,1.147488,1.025988,1.003691,0.996467,1.008140,1.084751,1.030484
2010-04-30,1.111021,0.949958,1.038514,0.975263,1.156910,1.003511,1.023014,0.978425,0.957721,1.009796,...,1.074892,0.820602,1.012964,1.077684,1.099291,1.067762,0.993617,0.948618,1.146197,1.025943
2010-05-31,0.983876,0.954762,0.982144,0.942587,0.860841,0.943655,0.942779,0.944873,0.903507,0.915098,...,0.996536,0.969676,0.945278,1.178244,1.066359,0.938870,1.079586,0.892185,0.972373,0.942069

Defining function to get 3 month, 6 month and 12 month returns

In [13]:
def get_rolling_ret(df, n):
    return df.rolling(n).apply(np.prod)

In [15]:
ret_12 = get_rolling_ret(ret_mtl,12)
ret_12.dropna(inplace=True) 
ret_12.head(3)

Ticker,AAPL,ADBE,ADI,ADP,ADSK,AEP,AMAT,AMD,AMGN,AMZN,...,SBUX,SMCI,SNPS,TMUS,TTWO,TXN,VRSK,VRTX,WBD,XEL
Date,,,,,,,,,,,,,,,,,,,,,
2010-12-31,1.507220,0.829873,1.223493,1.116250,1.488118,1.081273,1.004638,0.843299,0.951144,1.344287,...,1.413028,1.001736,1.199198,1.584693,1.179808,1.273197,1.141708,0.791817,1.345161,1.168597
2011-01-31,1.766739,1.023220,1.481500,1.213103,1.709962,1.081232,1.317179,1.049598,0.941860,1.352683,...,1.466822,1.136400,1.275505,2.296625,1.344828,1.533648,1.203058,1.012760,1.314902,1.186474
2011-02-28,1.726175,0.995671,1.402916,1.241332,1.508250,1.118131,1.371910,1.164349,0.906730,1.463598,...,1.465118,0.996003,1.265753,2.333873,1.670478,1.486341,1.143110,1.151209,1.383949,1.203362

In [16]:
ret_6 = get_rolling_ret(ret_mtl,6)
ret_6.dropna(inplace=True) 
ret_6.head(3)

Ticker,AAPL,ADBE,ADI,ADP,ADSK,AEP,AMAT,AMD,AMGN,AMZN,...,SBUX,SMCI,SNPS,TMUS,TTWO,TXN,VRSK,VRTX,WBD,XEL
Date,,,,,,,,,,,,,,,,,,,,,
2010-06-30,1.175319,0.712591,0.892526,0.955278,0.948968,0.947777,0.849287,0.754639,0.911296,0.815982,...,1.058597,1.171875,0.930036,1.027603,0.865385,0.903715,1.001675,0.743671,1.151935,1.000755
2010-07-31,1.339425,0.889164,1.118074,1.028217,1.241698,1.064595,0.978860,1.004021,0.932455,0.940037,...,1.145156,1.165456,1.026798,1.589698,1.104526,1.107513,1.055832,0.876562,1.301753,1.083179
2010-08-31,1.188056,0.799423,0.974707,0.942987,0.994620,1.079115,0.857322,0.709229,0.901607,1.054307,...,1.012507,0.602265,1.043836,1.448946,0.862786,0.952976,0.983039,0.821658,1.211878,1.097357

In [17]:
ret_3 = get_rolling_ret(ret_mtl,3)
ret_3.dropna(inplace=True) 
ret_3.head(3)

Ticker,AAPL,ADBE,ADI,ADP,ADSK,AEP,AMAT,AMD,AMGN,AMZN,...,SBUX,SMCI,SNPS,TMUS,TTWO,TXN,VRSK,VRTX,WBD,XEL
Date,,,,,,,,,,,,,,,,,,,,,
2010-03-31,1.098079,0.953626,0.916196,1.046439,1.144527,0.990318,0.946501,0.955670,1.036729,1.013966,...,1.052928,1.500000,0.996881,0.888331,0.949038,0.945614,0.944723,0.923825,1.090000,1.017285
2010-04-30,1.359418,1.040248,1.117710,1.071594,1.428752,1.002113,1.136819,1.215818,0.979993,1.093214,...,1.197229,1.144471,1.065350,1.355240,1.169181,1.161250,0.996444,1.009635,1.305799,1.058744
2010-05-31,1.255400,0.925830,1.012155,0.990165,1.049498,0.962742,1.061396,1.083439,0.914679,1.059628,...,1.134755,0.916056,0.978082,1.457050,1.202703,1.006190,1.068905,0.853231,1.208989,0.995972